- hosts: all
  remote_user: ansible
  become: yes
  become_method: "sudo"
  tasks:
    - name: start docker
      service:
        name: docker
        enabled: yes
        state: restarted

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: restarted

